import type {Metadata} from "next";
import {LoadingProvider} from '@/providers/loading.provider';
import Header from '@/components/header';
import "./globals.css";
import React, {JSX} from "react";
import PWAProvider from "@/providers/pwa.provider";

export const metadata: Metadata = {
    title: "Podcaster | List",
    description: "Generated by create next app",
};

/**
 * Root layout for the application.
 * @returns {JSX.Element} The root layout component.
 */
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>): JSX.Element {
    return (
        <html lang="en">
        <head>
            <link rel="preconnect" href="https://itunes.apple.com"/>
            <link rel="preconnect" href="https://api.codetabs.com"/>
            <link rel="preconnect" href="https://is1-ssl.mzstatic.com"/>
        </head>
        <body suppressHydrationWarning>
        <PWAProvider/>
        <LoadingProvider>
            <Header/>
            <main>{children}</main>
        </LoadingProvider>
        </body>
        </html>
    );
}
